version: '3.8'

services:
  frontend:
    image: sovit01/frontend:${TAG:-latest}
    restart: always
    ports:
      - "5001:3000"
    environment:
      - REACT_APP_API_URL=http://backend:5000
    depends_on:
      - backend

  backend:
    image: sovit01/backend:${TAG:-latest}
    restart: always
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/wanderlust
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    restart: always
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
